apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-service
  namespace: final
  labels:
    app: billing
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: final
  labels:
    app: order
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: final
  labels:
    app: notification
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentication-service
  namespace: final
  labels:
    app: auth
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: final
  labels:
    app: product
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delivery-service
  namespace: final
  labels:
    app: delivery
automountServiceAccountToken: true
