spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL}

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml


jwt:
  claims:
      exp:
        minutes: 30
  keys:
    private: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRGFuVEFCaWtYNnZkY1QKMXVlQWthOGIxZ09RQStPK2xCTE9BV1RmaVV6Z3JSTVMxV2pWMzJqckt4NDI4M0ptamtDL2hycitnemZiczc5TgpTMTZJVldlQzE4ZE9PYzh5ODFhbDlkZ3N4UVd0MjNMQmxhYytGazZHNnpLYnpkODJoRVBvUzhwdDFlNjV5VENLCkdsdEhMNnhEakZOWHNYenhRdjk3V0I1M2kwZ01BaVB5eGhhaWsybThiWG5uRnVpUUd5bXVsVjd3ZGRLVnk4S2EKbEpzcVFGOUNXMm9qY3Y4UGZlbE12aEdZUGNpU3VmeEJJWkttRU14N1NyemJVL3UrSlVQL3gzdkg4cWFFMDhCaQpncWdoODZEMHJYY0RhZUdKNXdwZ1liQzhnY0J0YndDTmN1bHZvenNERlZPMExkckxKdkxxakpXZ1BXK2lJby9TCnY0TWVLN1d2QWdNQkFBRUNnZ0VBVW1jVGxGRUpoYlVQSUJST1dNRVJMejNoUStTamNNK2hzdk1Ga2RqUUdKUkUKYjBIdjdVWHo1MGp1YjZvZUFoZzJ3YnJJTzIwOG5keklEQnVQdTNYdHVYMGFUQnN3UmJWQmdQY0ZFQU1IMi91dQo2dGM5SGdNTWdJQ2hKK2RXN3RhMlBoWnJiREZLZGM4bk03Y3hsc2lhZHkrcXJwQmhWeE40OTRaRW5henJjRktmCnR4SmdTeWIvNGFTdFRlT0xPUy83UEYwU0xHWDNNaVJmUUNhMDdtT2J6aFZOOEtXaVM5eFQydEQ3VEh1am1WOC8KSGlmMzZZc2dnYndQcnhoS2tTaVR1aG54aWlxOG1YcjZjRlB4bXdyYkFUNTgyNGpjQ3NoajhzMkd1WmVWcTVObgpNR3J5ZnhCVi9lVGhkUEVuYUM3dVQ0aGpuaEJXdFN6eEpRNGJlT2xJSVFLQmdRRDIwa1lBM3lKdmJTT2tod21VCnFCejJBd05IQW1QMERKSmtLaTJQT25QZEtzMkYrYVNURFp2Ujdlbmh5S2ZuSTc4aEl5TXNvL0VKOXlwV1lBa1UKRStDTGRCZ1VXM0s3aFdmREQ1SzJJdWIrMll2TTM0OGlNSytwSDdVVU9mbjQ1VDR5NjNGMmUyVDFPQ1k3WjJLcwo5aFRnclR4K3Z0S1NrSVhtT2hRL2Z1b0R2d0tCZ1FEaXZtR2xEeUZtS1krV2thRjZTSnN0aXNJRWJwekgyWjJBCjdBNCtoMGdBM2Y4VHN3eXAwWFhTQjRMTjFVdlRMeUpsZ0lQVlRZYVNYdHJjQjE3OS9qS2pjSGIxdC9ZRXQzeEgKL0s1ZVFvZDNlMEV3S24xait3clBtTmxkTzBLU1kyYWNhTzlBbHRlZGM3QXY2MXAwc1JqQ3ZUK2tQVFE0b2NiZwo1TnNpNG9RS0VRS0JnQWczdkFqdlpQQWN6Q0VBTmZ0ekZYUERhZXFGVTlxZVNJbDVOZ2NjeFJyS0FBbkQ1QXpaCldTVEdMUkZOWXZtNUlQWHplNHBTOHdXSDZ5cnhDNXhWaFJaZmlTVzBYYitNazRYVkVPZHJoaEZhSU9OelZncW4KWUZIYk1tWTMvL0NmZ1ZDa3NpUmx1MWpHdzg4YWhCaUtJT3ZTR0wrSGp1OCtUSmI3dkF6Wkp1VjFBb0dCQUp6NgpLU2ZZL2NwNDQ0dmVidWoxODFqb1E4SkZ3ZzBxUDd6TnNGN2gwWnVvRmJ4UnJXYTBPTm1ia1pkbklBT3BFaXNyCmVobm1mbEEvazAzWlhJNkR1aE1rL1hiSVVXNmFpVlJkUDJyS3JIYXZ3a1hTWk5VZkxERGxKVGRDbTZnMVlRalEKTFRPT091QXJBOE5wTVVxd2dPL3hqV25yWllmL21HeUNoS1AySm12QkFvR0JBSlRheHlvdC9YWmR3K2xHMVpDcApCOUQrTmxWR1FhV1F0Z2xsZW1CU0o5TUM1SXlINXV6cGpTRmVBcXR3UWZlb0Z1UkNoanhHcGdWZ1YvQ2pVOExMCnBoekdIWWxjcDF4bTVQMm0vVmdGVE8vQ2UxZDNBMUNUMWYxMXg1TUVkYURBbWx4ZEZ2ZCtZZGhOb3JnRVBEcXUKWTljaDFOTWZIdnlsRlNFT2hwQXZJUG4vCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
    public: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEycDB3QVlwRityM1hFOWJuZ0pHdgpHOVlEa0FQanZwUVN6Z0ZrMzRsTTRLMFRFdFZvMWQ5bzZ5c2VOdk55Wm81QXY0YTYvb00zMjdPL1RVdGVpRlZuCmd0ZkhUam5QTXZOV3BmWFlMTVVGcmR0eXdaV25QaFpPaHVzeW04M2ZOb1JENkV2S2JkWHV1Y2t3aWhwYlJ5K3MKUTR4VFY3Rjg4VUwvZTFnZWQ0dElEQUlqOHNZV29wTnB2RzE1NXhib2tCc3BycFZlOEhYU2xjdkNtcFNiS2tCZgpRbHRxSTNML0QzM3BUTDRSbUQzSWtybjhRU0dTcGhETWUwcTgyMVA3dmlWRC84ZDd4L0ttaE5QQVlvS29JZk9nCjlLMTNBMm5oaWVjS1lHR3d2SUhBYlc4QWpYTHBiNk03QXhWVHRDM2F5eWJ5Nm95Vm9EMXZvaUtQMHIrREhpdTEKcndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

auth:
  security:
    salt:
      length: 32 # Max = 64 (check liquibase change-set 1)
    bcrypt:
      strength: 10

springfox:
  documentation:
    swagger-ui:
      base-url: "/documentation"

external:
  business:
    url: "127.0.0.1:8000"
    endpoints:
      create: "/create"
