kafka:
  bootstrapAddress: "localhost:9092"
  applicationId: "order-service"
  schema:
    registry:
      url: "http://localhost:8081"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order
      authentication-database: order
      auto-index-creation: true


service:
  order:
    idempotency:
      ttl: 10s

server:
  port: 7006